site_name: VideoMaker-Helper
repo_url: https://github.com/dunossauro/videomaker-helper
repo_name: videomaker-helper

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
plugins:
  - mkdocs-video:
      is_video: True
      video_type: mp4
  - mkdocstrings:
      handlers:
        python:
          paths: [videomaker_helper]

watch:
   - videomaker_helper
