name: Pipeline
on:
  push:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Update ubuntu
        run: sudo apt update

      - name: Install ffmpeg
        run: sudo apt install ffmpeg -y

      - name: Install poetry
        run: pipx install --python python3.11 poetry

      - name: Install dependencies
        run: poetry install --without doc

      - name: Check ruff
        run: poetry run task lint

      - name: Mypy check
        run: poetry run task types

      - name: Typos check
        run: poetry run task typos

      - name: Pytest
        run: poetry run task test
